[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA"
linker = "flip-link"
rustflags = [
  "-C", "link-arg=--defsym=__bootloader_config_nfc_pins_as_gpio=1",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
KEYBOARD_TOML_PATH = { value = "keyboard.toml", relative = true }
RUST_MIN_STACK = "16777216"
